=== Glecun/glecun/cv/cv_greg.dtd
<!ELEMENT cv (lang,general,formations,realisations,experiences,competences,autres)>
<!ELEMENT lang (#PCDATA)>

<!ELEMENT general (nom,prenom,emploi_actuelle,description,adresse,telephone,url_site,email,url_photo)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT emploi_actuelle (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT url_site (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url_photo (#PCDATA)>

<!ELEMENT formations (diplome+)>
<!ELEMENT diplome (nom,lieu_obtention,annee,description)>
<!ELEMENT lieu_obtention (#PCDATA)>
<!ELEMENT annee (#PCDATA)>

<!ELEMENT realisations (projet+)>
<!ELEMENT projet (nom,lieu,date,description,url_sources)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT url_sources (#PCDATA)>
<!ELEMENT date (jour,mois,annee)>
<!ELEMENT jour (#PCDATA)>
<!ELEMENT mois (#PCDATA)>

<!ELEMENT experiences (experience+)>
<!ELEMENT experience (nom_poste,nom_entreprise,periode,description)>
<!ELEMENT nom_poste (#PCDATA)>
<!ELEMENT nom_entreprise (#PCDATA)>
<!ELEMENT periode (date,date)>

<!ELEMENT competences (groupe+)>
<!ELEMENT groupe (nom,competence+)>
<!ELEMENT competence (nom,percent)>
<!ELEMENT percent (#PCDATA)>

<!ELEMENT autres (langues,hobbies)>
<!ELEMENT langues (langue+)>
<!ELEMENT langue (nom,niveau)>
<!ELEMENT hobbies (hobbie+)>
<!ELEMENT hobbie (nom,niveau)>
<!ELEMENT niveau (#PCDATA)>

=== Glecun/glecun/cv/cv_greg.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="cv_greg.xsl" type="text/xsl" ?>

<!DOCTYPE cv SYSTEM "cv_greg.dtd"> 
<cv xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com cv_greg.xsd">
	<lang>FR</lang>
	<general>
		<nom>Le Cun</nom>
		<prenom>Grégoire</prenom>
		<emploi_actuelle>Développeur Web Full-Stack</emploi_actuelle>
		<description>
			Passionné depuis <![CDATA[<span id="years-of-experience"></span>]]> ans, je parcours sans cesse les différents horizons que m’offre l’informatique tels que le mobile, les jeux vidéo ou encore le web.
			<![CDATA[<br/><br/>]]>
			Lorsqu’une idée d’application me vient en tête, je n’hésite jamais à la réaliser sur mon temps libre en me confrontant à une nouvelle technologie en vogue.
			<![CDATA[<br/><br/>]]>
			J’ai dans ma carrière, eu la chance de pouvoir assister à des conférences telles que Devoxx France ou Codeurs En Seine. Je me tiens également à jour en visionnant de moi-même des conférences en ligne ou en participant à des événements les soirs de semaine.
			<![CDATA[<br/><br/>]]>
			Je suis actuellement Développeur Full-Stack orienté Web avec un fort attrait pour les technologies Front-end. Je suis parfaitement capable de travailler en équipe dans un environnement agile et être force de proposition.
		</description>
		<adresse>Eaubonne, 95600</adresse>
		<telephone/>
		<url_site>http://glecun.fr</url_site>
		<email>gregoire.lecun@free.fr</email>
		<url_photo>http://glecun.fr/img/me2.jpg</url_photo>
	</general>
	<formations>
		<diplome>
			<nom>Diplôme d’ingénieur Informatique &amp; Réseaux</nom>
			<lieu_obtention>Université Paris 13, Ecole Sup’Galilée</lieu_obtention>
			<annee>2014 - 2017</annee>
			<description>Diplôme d’ingénieur en Informatique &amp; Réseaux en apprentissage réalisé en alternance à la Direction des Systèmes Informatiques de Foncia</description>
		</diplome>
		<diplome>
			<nom>DUT Informatique</nom>
			<lieu_obtention>Université Paris 13, IUT de Villetaneuse</lieu_obtention>
			<annee>2012 - 2014</annee>
			<description>DUT Informatique réalisé en alternance à la Direction des Systèmes Informatiques à Foncia.</description>
		</diplome>
	</formations>
	<realisations>
		<projet>
			<nom>ColorLine</nom>
			<lieu>Projet personnel</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2016 - 2017</annee>
			</date>
			<description>Jeu de reflexion pour Android réalisé avec Unity</description>
			<url_sources>https://play.google.com/store/apps/details?id=com.gle.colorline</url_sources>
		</projet>
		<projet>
			<nom>GlecunTech</nom>
			<lieu>Projet personnel</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2016</annee>
			</date>
			<description>Site web réalisé "from scratch" qui liste l'ensemble des technologies que j'utilise.</description>
			<url_sources>http://gregoire.lecun.free.fr/glecuntech/</url_sources>
		</projet>
		<projet>
			<nom>Site de Gîte/Chambres d'hôtes</nom>
			<lieu>Projet pour un client</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2014 - 2020</annee>
			</date>
			<description>Réalisation et maintenance d'un site vitrine réalisé avec Wordpress pour un domaine possédant des gîtes et des chambres d'hôtes</description>
		</projet>
		<projet>
			<nom>Jeu Space Invaders</nom>
			<lieu>Ecole Sup’Galilée</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2015</annee>
			</date>
			<description>Jeu réalisé en Java graphique dans le cadre de ma formation d'ingénieur Informatique &amp; Réseaux.</description>
			<url_sources>http://glecun.fr/#projects</url_sources>
		</projet>
		<projet>
			<nom>Jeux Pygame</nom>
			<lieu>Projet personnel</lieu>
			<date>
				<jour>01</jour>
				<mois>Mars</mois>
				<annee>2013</annee>
			</date>
			<description>Jeux réalisés en Python orienté objet avec la librairie graphique Pygame par envie personnel.</description>		
			<url_sources>http://glecun.fr/#projects</url_sources>
		</projet>
	</realisations>
	<experiences>
		<experience>
			<nom_poste>Développeur Web Full-Stack</nom_poste>
			<nom_entreprise>VIDAL</nom_entreprise>
			<periode>
				<date>
					<jour></jour>
					<mois/>
					<annee>2017</annee>
				</date>
				<date>
					<jour></jour>
					<mois/>
					<annee>aujourd'hui</annee>
				</date>
			</periode>
			<description>
				Développement d'applications Web Java / Angular à destination des scientifiques, des laboratoires et des éditeurs de VIDAL. J'ai agis au sein d'une DSI très sensible à l'agilité avec une réelle intention de toujours s'améliorer.
				Mon travail a été : analyse technique et conception, estimations des solutions, développements et tests (TDD / Pair Programming)
				<![CDATA[<br/><br/>]]>
				Environnement technique : Java 8 - 10, Angular 7, AngularJs, Jasmine, Hibernate, Spring, JUnit / Mockito / Cucumber, MongoDB, Maven, Git, Sonar
			</description>
		</experience>
		<experience>
			<nom_poste>Développeur Web Java</nom_poste>
			<nom_entreprise>Foncia Groupe</nom_entreprise>
			<periode>
				<date>
					<jour></jour>
					<mois/>
					<annee>2014</annee>
				</date>
				<date>
					<jour></jour>
					<mois/>
					<annee>2017</annee>
				</date>
			</periode>
			<description>Branchement d’un moteur de recherche ElasticSearch sur une application web réalisée avec la technologie JSF2 en Java et opération de maintenance évolutive et corrective des applications de Foncia essentiellement sur le domaine de la prospection.</description>
		</experience>
		<experience>
			<nom_poste>Administrateur Système &amp; Développeur Web PHP</nom_poste>
			<nom_entreprise>Foncia Groupe</nom_entreprise>
			<periode>
				<date>
					<jour></jour>
					<mois/>
					<annee>2012</annee>
				</date>
				<date>
					<jour></jour>
					<mois/>
					<annee>2014</annee>
				</date>
			</periode>
			<description>Lors de ma première année à Foncia, occupation d’un poste d'Administrateur Système pour la mise en place des automatismes de création d'environnement dans le Cloud. La solution devait fournir aux développeurs un environnement de recette comprenant plusieurs services (Apache, Tomcat, FTP, SQL, etc...). Puis la seconde année, intégration de l'équipe de développeur PHP pour le développement d'une application réalisée avec la technologie Symfony2 et opérer de la maintenance évolutive et corrective des applications de Foncia.</description>
		</experience>
	</experiences>
	<competences>
		<groupe>
			<nom>Languages / Frameworks</nom>
			<competence><nom>Java</nom><bold>true</bold></competence>
			<competence><nom>Angular</nom><bold>true</bold></competence>
			<competence><nom>Html / CSS</nom></competence>
			<competence><nom>AngularJs</nom></competence>
			<competence><nom>React</nom></competence>
		</groupe>
		<groupe>
			<nom>Tests</nom>
			<competence><nom>JUnit</nom><bold>true</bold></competence>
			<competence><nom>AssertJ</nom><bold>true</bold></competence>
			<competence><nom>Mockito</nom><bold>true</bold></competence>
			<competence><nom>Jasmine</nom></competence>
			<competence><nom>Jest</nom><bold>true</bold></competence>
			<competence><nom>Cucumber</nom></competence>
		</groupe>
		<groupe>
			<nom>Bases de Données</nom>
			<competence><nom>MongoDb</nom><bold>true</bold></competence>
			<competence><nom>PostgreSQL</nom><bold>true</bold></competence>
			<competence><nom>SQL Server</nom></competence>
		</groupe>
		<groupe>
			<nom>Outils</nom>
			<competence><nom>Intellij</nom><bold>true</bold></competence>
			<competence><nom>Git</nom><bold>true</bold></competence>
			<competence><nom>Docker</nom></competence>
			<competence><nom>Gradle</nom></competence>
			<competence><nom>Maven</nom></competence>
			<competence><nom>Jenkins</nom></competence>
			<competence><nom>Npm</nom></competence>
			<competence><nom>RabbitMQ</nom></competence>
		</groupe>
		<groupe>
			<nom>Software Craftsmanship</nom>
			<competence><nom>TDD</nom><bold>true</bold></competence>
			<competence><nom>Pair Programming</nom><bold>true</bold></competence>
			<competence><nom>Scrum</nom></competence>
			<competence><nom>Kanban</nom></competence>
			<competence><nom>Mob Programming</nom></competence>
		</groupe>
		<groupe>
			<nom>Connaissances non avancées</nom>
			<competence><nom>Vue.js</nom></competence>
			<competence><nom>Wordpress</nom></competence>
			<competence><nom>VertX</nom></competence>
			<competence><nom>ElasticSearch</nom></competence>
			<competence><nom>Symfony2</nom></competence>
		</groupe>
		<groupe>
			<nom>Jeux Vidéo</nom>
			<competence><nom>Unity</nom></competence>
			<competence><nom>Game Maker studio 2</nom></competence>
		</groupe>
	</competences>
	<autres>
		<langues>
			<langue>
				<nom>Anglais</nom>
				<niveau>(TOEIC: 830pts)</niveau>
			</langue>
		</langues>
		<hobbies>
			<hobbie>
				<nom>Jeux vidéo</nom>
				<niveau/>
				<icon>gamepad</icon>
			</hobbie>
			<hobbie>
				<nom>Jeux de société</nom>
				<niveau/>
				<icon>dice</icon>
			</hobbie>
			<hobbie>
				<nom>Guitare-Basse/Guitare</nom>
				<niveau/>
				<icon>music</icon>
			</hobbie>
			<hobbie>
				<nom>Salle de sport</nom>
				<niveau/>
				<icon>dumbbell</icon>
			</hobbie>
		</hobbies>
	</autres>
</cv>

=== Glecun/glecun/cv/cv_greg_en.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="cv_greg.xsl" type="text/xsl" ?>

<!DOCTYPE cv SYSTEM "cv_greg.dtd">
<cv xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com cv_greg.xsd">
	<lang>EN</lang>
	<general>
		<nom>Le Cun</nom>
		<prenom>Grégoire</prenom>
		<emploi_actuelle>Web Junior Developer</emploi_actuelle>
		<description>I'm a 22 years old apprentice currently under a study contract in Foncia Group as a JAVA developer as part of the preparation of my computer engineer degree.</description>
		<adresse>Eaubonne, 95600</adresse>
		<telephone/>
		<url_site>http://glecun.fr</url_site>
		<email>gregoire.lecun@gmail.com</email>
		<url_photo>http://glecun.fr/img/me.jpg</url_photo>
	</general>
	<formations>
		<diplome>
			<nom>Engineering Degree</nom>
			<lieu_obtention>University Paris 13, School Sup’Galilée</lieu_obtention>
			<annee>2014 - 2017</annee>
			<description>It's currently my third year of my engineering degree performed in sandwich training. I'm engaged with Foncia Group for 3 years as an apprentice in our IT System Department.</description>
		</diplome>
		<diplome>
			<nom>Higher Diploma</nom>
			<lieu_obtention>University Paris 13, IUT of Villetaneuse</lieu_obtention>
			<annee>2012 - 2014</annee>
			<description>Higher National Diploma realized in sandwich training in the IT System Department of Foncia Group.</description>
		</diplome>
	</formations>
	<realisations>
		<projet>
			<nom>ColorLine</nom>
			<lieu>Personal project</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2016 - 2017</annee>
			</date>
			<description>Puzzle game for Android realized with Unity</description>
			<url_sources>https://play.google.com/store/apps/details?id=com.gle.colorline</url_sources>
		</projet>
		<projet>
			<nom>GlecunTech</nom>
			<lieu>Personal project</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2016</annee>
			</date>
			<description>Web site realized "from scratch" which a list of all the technologies that I currently use.</description>
			<url_sources>http://gregoire.lecun.free.fr/glecuntech/</url_sources>
		</projet>
		<projet>
			<nom>Website of Gîte/Bed and Breakfast</nom>
			<lieu>Project for a client</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2014 - Today</annee>
			</date>
			<description>Realization and maintenance of a showcase site realized with Wordpress for a domain with gites and bed and breakfasts</description>
			<url_sources>http://www.lecocondecurson.fr/</url_sources>
		</projet>
		<projet>
			<nom>Space Invaders Game</nom>
			<lieu>School Sup’Galilée</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2015</annee>
			</date>
			<description>Game realized in Java graphic as part of my training of Computer Science &amp; Networks Engineer degree.</description>
			<url_sources>http://glecun.fr/#projects</url_sources>
		</projet>
		<projet>
			<nom>Pygame Games</nom>
			<lieu>Personal Project</lieu>
			<date>
				<jour>01</jour>
				<mois>March</mois>
				<annee>2013</annee>
			</date>
			<description>Project realized by personal desire in Python object oriented with the graphic library Pygame.</description>
			<url_sources>http://glecun.fr/#projects</url_sources>
		</projet>
	</realisations>
	<experiences>
		<experience>
			<nom_poste>Web Developer Java</nom_poste>
			<nom_entreprise>Foncia Group</nom_entreprise>
			<periode>
				<date>
					<jour></jour>
					<mois/>
					<annee>2014</annee>
				</date>
				<date>
					<jour></jour>
					<mois/>
					<annee>2017</annee>
				</date>
			</periode>
			<description>Connection of an ElasticSearch search engine on a web application realized with JSF2 technology in Java and also a evolutionary and corrective operation of Foncia applications mainly in the area of ​​prospecting.</description>
		</experience>
		<experience>
			<nom_poste>System Administrator &amp; Web Developer</nom_poste>
			<nom_entreprise>Foncia Group</nom_entreprise>
			<periode>
				<date>
					<jour></jour>
					<mois/>
					<annee>2012</annee>
				</date>
				<date>
					<jour></jour>
					<mois/>
					<annee>2014</annee>
				</date>
			</periode>
			<description>During my first year at Foncia, I was a System Administrator for the implementation of environmental building automation in the cloud. The solution was to provide developers with a recipe environment with multiple services (Apache, Tomcat, FTP, SQL, etc). Then for the second year, I worked for a PHP developer team to develop an application realized with Symfony2 technologies and to operate the evolutionary and corrective maintenance of all Foncia applications.</description>
		</experience>
	</experiences>
	<competences>
		<groupe>
			<nom>Web Conception</nom>
			<competence>
				<nom>J2E / JSF2</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>PHP</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>Html 5 / CSS 3</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>JQuery / Javascript</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>Symfony2</nom>
				<percent>40</percent>
			</competence>
			<competence>
				<nom>Wordpress</nom>
				<percent>60</percent>
			</competence>
		</groupe>
		<groupe>
			<nom>Data</nom>
			<competence>
				<nom>BDD Conception</nom>
				<percent>60</percent>
			</competence>
			<competence>
				<nom>SQL</nom>
				<percent>70</percent>
			</competence>
			<competence>
				<nom>ElasticSearch</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>XML/XSD/DTD/XSLT</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>UML</nom>
				<percent>40</percent>
			</competence>
		</groupe>
		<groupe>
			<nom>System Administration</nom>
			<competence>
				<nom>Bash/UNIX/Shell</nom>
				<percent>70</percent>
			</competence>
			<competence>
				<nom>Apache</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>Puppet</nom>
				<percent>40</percent>
			</competence>
			<competence>
				<nom>Amazon AWS</nom>
				<percent>50</percent>
			</competence>
		</groupe>
		<groupe>
			<nom>Langages</nom>
			<competence>
				<nom>Python</nom>
				<percent>60</percent>
			</competence>
			<competence>
				<nom>C / C++</nom>
				<percent>70</percent>
			</competence>
			<competence>
				<nom>C#</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>Ruby</nom>
				<percent>20</percent>
			</competence>
			<competence>
				<nom>Unity</nom>
				<percent>60</percent>
			</competence>
		</groupe>
	</competences>
	<autres>
		<langues>
			<langue>
				<nom>English</nom>
				<niveau>(TOEIC: 830pts)</niveau>
			</langue>
		</langues>
		<hobbies>
			<hobbie>
				<nom>Guitar-Bass/Guitar</nom>
				<niveau/>
			</hobbie>
			<hobbie>
				<nom>Running</nom>
				<niveau/>
			</hobbie>
		</hobbies>
	</autres>
</cv>

=== Glecun/glecun/cv/cv_greg_ja.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="cv_greg.xsl" type="text/xsl" ?>

<!DOCTYPE cv SYSTEM "cv_greg.dtd"> 
<cv xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com cv_greg.xsd">
	<lang>JA</lang>
	<general>
		<nom>Le Cun</nom>
		<prenom>Grégoire</prenom>
		<emploi_actuelle>ジュニアWeb開発者</emploi_actuelle>
		<description>見習い22年は今交互にコンピュータサイエンス＆アンペアで工学の学位の準備の一環としてのJava Web開発者としてFonciaグループで契約します。ネットワーク内の交替</description>
		<adresse>Eaubonne, 95600</adresse>
		<telephone/>
		<url_site>http://glecun.fr</url_site>
		<email>gregoire.lecun@free.fr</email>
		<url_photo>http://glecun.fr/img/me2.jpg</url_photo>
	</general>
	<formations>
		<diplome>
			<nom>工学の学位コンピュータ &amp; ネットワーク</nom>
			<lieu_obtention>パリ13大学、エコールSup'Galilée</lieu_obtention>
			<annee>2014 - 2017</annee>
			<description>コンピュータトレーニング＆アンペアでのエンジニアリングスクールの1年目で、情報システムFonciaの理事で交互に行わラーニングネットワーク</description>
		</diplome>
		<diplome>
			<nom>DUTのInformatique</nom>
			<lieu_obtention>Villetaneuseの大学パリ13 IUT</lieu_obtention>
			<annee>2012 - 2014</annee>
			<description>DUTのInformatiqueはFonciaで情報システムの理事で交互に行います。</description>
		</diplome>
	</formations>
	<realisations>
		<projet>
			<nom>ColorLine</nom>
			<lieu>個人的なプロジェクト</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2016 - 2017</annee>
			</date>
			<description>Android用パズルゲームは、Unityと作られました</description>
			<url_sources>https://play.google.com/store/apps/details?id=com.gle.colorline</url_sources>
		</projet>
		<projet>
			<nom>GlecunTech</nom>
			<lieu>個人的なプロジェクト</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2016</annee>
			</date>
			<description>私が使用するすべての技術が一覧表示されます「ゼロから」設計されたWebサイト。</description>
			<url_sources>http://gregoire.lecun.free.fr/glecuntech/</url_sources>
		</projet>
		<projet>
			<nom>コテージサイト/ゲストハウス</nom>
			<lieu>クライアントのためのプロジェクト</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2014 - 今日</annee>
			</date>
			<description>ロッジやコテージでドメインのWordpressので作られたショーケースのウェブサイトの構築と保守</description>
			<url_sources>http://www.lecocondecurson.fr/</url_sources>
		</projet>
		<projet>
			<nom>スペースインベーダーゲーム</nom>
			<lieu>学校 Sup’Galilée</lieu>
			<date>
				<jour></jour>
				<mois></mois>
				<annee>2015</annee>
			</date>
			<description>ゲームは私のコンピュータ＆＃038エンジニアリングトレーニングの下でJavaグラフィックスで行われました。ネットワーク。</description>
			<url_sources>http://glecun.fr/#projects</url_sources>
		</projet>
		<projet>
			<nom>pygameのゲーム</nom>
			<lieu>個人的なプロジェクト</lieu>
			<date>
				<jour>01</jour>
				<mois>3月</mois>
				<annee>2013</annee>
			</date>
			<description>グラフィックライブラリpygameの羨望の担当者で作られたPythonオブジェクト指向のゲーム。</description>		
			<url_sources>http://glecun.fr/#projects</url_sources>
		</projet>
	</realisations>
	<experiences>
		<experience>
			<nom_poste>Java Web開発者向け</nom_poste>
			<nom_entreprise>FonciaのGroupe</nom_entreprise>
			<periode>
				<date>
					<jour></jour>
					<mois/>
					<annee>2014</annee>
				</date>
				<date>
					<jour></jour>
					<mois/>
					<annee>2017</annee>
				</date>
			</periode>
			<description>主に探査のフィールド上のJava技術とJSF2プログレッシブ及び是正保守アプリケーションFonciaで開発されたWebアプリケーションにElasticSearch検索エンジンを接続します。</description>
		</experience>
		<experience>
			<nom_poste>システム管理者 &amp; PHPのWeb開発者</nom_poste>
			<nom_entreprise>FonciaのGroupe</nom_entreprise>
			<periode>
				<date>
					<jour></jour>
					<mois/>
					<annee>2012</annee>
				</date>
				<date>
					<jour></jour>
					<mois/>
					<annee>2014</annee>
				</date>
			</periode>
			<description>Foncia、クラウドの環境ビルオートメーションの実装のためのシステム管理者の位置の占領で私の最初の年の間に。解決策は、開発者に複数のサービス（のApache、Tomcatの、FTP、SQLなど）を持つレシピ環境を提供することでした。そして二年目、Symfony2の技術で開発されたアプリケーションの開発のためのPHP開発者のチームを統合し、アプリケーションFonciaの進化論と是正保守を運営しています。</description>
		</experience>
	</experiences>
	<competences>
		<groupe>
			<nom>ウェブデザイン</nom>
			<competence>
				<nom>J2E / JSF2</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>PHP</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>Html 5 / CSS 3</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>JQuery / Javascript</nom>
				<percent>90</percent>
			</competence>
			<competence>
				<nom>Symfony2</nom>
				<percent>40</percent>
			</competence>
			<competence>
				<nom>Wordpress</nom>
				<percent>60</percent>
			</competence>
		</groupe>
		<groupe>
			<nom>データ</nom>
			<competence>
				<nom>データベース設計</nom>
				<percent>60</percent>
			</competence>
			<competence>
				<nom>SQL</nom>
				<percent>70</percent>
			</competence>
			<competence>
				<nom>ElasticSearch</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>XML/XSD/DTD/XSLT</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>UML</nom>
				<percent>40</percent>
			</competence>
		</groupe>
		<groupe>
			<nom>行政システム</nom>
			<competence>
				<nom>Bash/UNIX/Shell</nom>
				<percent>70</percent>
			</competence>
			<competence>
				<nom>Apache</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>Puppet</nom>
				<percent>40</percent>
			</competence>
			<competence>
				<nom>Amazon AWS</nom>
				<percent>50</percent>
			</competence>
		</groupe>
		<groupe>
			<nom>言語</nom>
			<competence>
				<nom>Python</nom>
				<percent>60</percent>
			</competence>
			<competence>
				<nom>C / C++</nom>
				<percent>70</percent>
			</competence>
			<competence>
				<nom>C#</nom>
				<percent>50</percent>
			</competence>
			<competence>
				<nom>Ruby</nom>
				<percent>20</percent>
			</competence>
			<competence>
				<nom>Unity</nom>
				<percent>60</percent>
			</competence>
		</groupe>
	</competences>
	<autres>
		<langues>
			<langue>
				<nom>英語</nom>
				<niveau>(TOEIC: 830pts)</niveau>
			</langue>
		</langues>
		<hobbies>
			<hobbie>
				<nom>ギター・ベース/ギター</nom>
				<niveau/>			
			</hobbie>
			<hobbie>
				<nom>ランニング</nom>
				<niveau/>			
			</hobbie>
		</hobbies>
	</autres>
</cv>
